### ISSUE TITLE
pip install failure on python 3.12.3 in `aarch64-darwin`

### ISSUE THREAD

**Issue by yzx9** [SEU-ALLEN-codebase/v3d-py-helper#3]
I encountered an error while trying to install v3d-py-helper using pip on Python 3.12.3 in an aarch64-darwin environment. However, installing version 0.1.0 works correctly.

The error appears to be caused by an issue in the package's build process, specifically related to the packaging of binary files. The missing directory suggests that a required dependency or file path is not correctly included or referenced in the build scripts. This could be due to incorrect setup configurations or a problem in the source distribution.

Any insights or suggestions to resolve this issue would be greatly appreciated.

## Steps to Reproduce:

1. Use Python 3.12.3 on an aarch64-darwin system.
2. Run the command pip install v3d-py-helper.

## Expected Behavior

The package should install successfully without errors.

## Actual Behavior

The installation fails with a subprocess-exited-with-error due to a missing directory.

```
› pip install v3d-py-helper       
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting v3d-py-helper
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ee/a2/0d06d0f0430c9c1d9aa1bcf16aa474f0322f3f6bb24ac018020120f95cec/v3d-py-helper-0.3.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/yzx9/git/xxx/.direnv/python-3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yzx9/git/xxx/.direnv/python-3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yzx9/git/xxx/.direnv/python-3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/hc/ghcd_3c17px43sk9mv9x82mh0000gn/T/pip-build-env-et8hxabr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/hc/ghcd_3c17px43sk9mv9x82mh0000gn/T/pip-build-env-et8hxabr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/hc/ghcd_3c17px43sk9mv9x82mh0000gn/T/pip-build-env-et8hxabr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 308, in <module>
        File "/private/var/folders/hc/ghcd_3c17px43sk9mv9x82mh0000gn/T/pip-build-env-et8hxabr/overlay/lib/python3.12/site-packages/cmake_build_extension/cmake_extension.py", line 48, in __init__
          raise ValueError(f"Directory '{source_dir}' does not exist")
      ValueError: Directory '/private/var/folders/hc/ghcd_3c17px43sk9mv9x82mh0000gn/T/pip-install-7_f0vqqr/v3d-py-helper_5768e9261bdb41529af46e6e414c7d31/3rdparty/libtiff' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by zzhmark** [comment]
I haven't tried building the package on Darwin. Indeed, as the new version introduces building tiff dependencies (for terafly), the building error can be expected. I am not sure if I correct it, but judging from the debugging output the libtiff source or build seems to be missing.

In my building process, the libtiff source is first cloned and built, and then the package gets built. But actually it has been done in the github workflow, so that's why windows and linux systems can quickly get the package installed.

![image](https://github.com/user-attachments/assets/ef58c00d-d9ea-4d7f-81fe-9ded65d2b7f9)

I am sorry, but for Darwin, you might have to install it from scratch. This error may occur when, for example, the libtiff cannot be properly cloned, which is quite common in China for bad connection with GitHub.

I can actually add Darwrin systems into the Workflow matrix, but I can't make sure that it really works.

**Comment by zzhmark** [comment]
I'm testing the build on Darwin (macos 13 & 14), you may try install it when it's ready

**Comment by zzhmark** [comment]
It can be installed on major 13& 14 now.
